config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'search#index', as: 'search'
  patch 'repos/:id', to: 'repos#private_fiture', as: 'private_fiture', :via => :update
  resources :profiles, only: :show
  resources :repos do
    resources :folders, only: [:show, :create, :destroy]
    resources :items, only: [:show, :create, :destroy]
  end
  get '/moon', to: 'application#moon', as: 'moon'
  get '/sun', to: 'application#sun', as: 'sun'
  get 'pages/index'
  devise_for :users
  root "pages#index"
end

app/models/repo.rb
class Repo < ApplicationRecord
    belongs_to :user
    has_many :folders, dependent: :destroy
    has_many :items, dependent: :destroy
    validates :name, presence: true, length: { maximum: 150 }
    validates :body, length: { maximum: 350 }
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_action :authenticate_user!
  before_action :set_repo, only: %i[ show edit update destroy private_fiture show_public ]
  before_action :correct_user, only: [:edit, :update, :destroy, :private_fiture]
  before_action :show_public, only: [:show]

  # GET /repos or /repos.json
  def index
    @repos = Repo.page(params[:page]).per(9)
    @repo = current_user.repos.build
  end

  # GET /repos/1 or /repos/1.json
  def show
  end

  # GET /repos/new
  def new
    @repo = current_user.repos.build
  end

  # GET /repos/1/edit
  def edit
  end

  # POST /repos or /repos.json
  def create
    @repo = current_user.repos.build(repo_params)

    respond_to do |format|
      if @repo.save
        format.html { redirect_to repo_url(@repo), notice: "Repo was successfully created." }
        format.json { render :show, status: :created, location: @repo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repos/1 or /repos/1.json
  def update
    respond_to do |format|
      if @repo.update(repo_params)
        format.html { redirect_to repo_url(@repo), notice: "Repo was successfully updated." }
        format.json { render :show, status: :ok, location: @repo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repos/1 or /repos/1.json
  def destroy
    @repo.destroy

    respond_to do |format|
      format.html { redirect_to repos_url, notice: "Repo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def private_fiture
    if @repo.private_role == true
      @repo.update_attribute(:private_role, false)
      @repo.folders.update_all(private_role: false)
      @repo.items.update_all(private_role: false)
    elsif @repo.private_role == false
      @repo.update_attribute(:private_role, true)
      @repo.folders.update_all(private_role: false)
      @repo.items.update_all(private_role: true)
    end
    redirect_to request.referrer
  end

  private
  def show_public
    redirect_to repos_path, notice: "This repo is private!" if @repo.private_role == true unless current_user.id == @repo.user_id
  end

  def correct_user
    @repo = current_user.repos.find_by_id(params[:id])
    # @repo = current_user.repos.find_by_slug(params[:id])
    redirect_to repos_path, notice: "Not authorized to edit this repo" if @repo.nil?
  end
  
  # Use callbacks to share common setup or constraints between actions.
  def set_repo
    @repo = Repo.find(params[:id]) rescue not_found
  end

  # Only allow a list of trusted parameters through.
  def repo_params
    params.require(:repo).permit(:name, :user_id, :body)
  end
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/repos/_form.html.erb
<%= form_with(model: repo) do |form| %>
  <% if repo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(repo.errors.count, "error") %> prohibited this repo from being saved:</h2>

      <ul>
        <% repo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="mb-3">
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/repos/_repo.html.erb
<div class="col">
  <div id="<%= dom_id repo %>">
    <div class="col">
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col">
                <% if repo.private_role == true %>
                  <span class="badge text-bg-danger">Private</span> <i class="bi bi-lock-fill"></i>
                <% elsif repo.private_role == false %>
                  <span class="badge text-bg-warning">Public</span> <% if params[:action] == 'show' %><i class="bi bi-unlock-fill"></i><% end %>
                <% end %>
                <h5 class="card-title">
                  <%= link_to repo.name, repo, class:"text-decoration-custom" %>
                </h5>
              </div>
              <div class="col text-end">
                <% if repo.user.id == current_user.id %>
                <button type="button" class="btn" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="bi bi-three-dots-vertical"></i>
                </button>
                <ul class="dropdown-menu dropdown-menu-end">
                  <li>
                    <a class="" href="#">
                      <%= link_to 'Edit', edit_repo_path(repo), class:"dropdown-item" %>
                    </a>
                  </li>
                  <li>
                    <a class="" href="#">
                      <%= link_to 'Destroy', repo, data: { turbo: true, turbo_confirm: 'Are you sure?', turbo_method: :delete }, class:"dropdown-item" %>
                    </a>
                  </li>
                </ul>
                <% end %>
              </div>
              <p class="card-text">
                <%= truncate(repo.body, length: 150) %>
              </p>
              <small class="text-muted disabled">
                created by <%= repo.user.username %> <%= time_ago_in_words(repo.created_at) %> ago
              </small>
              <% if params[:action] == 'show' %>
                <% if current_user.id == repo.user.id %>
                  <%= link_to repo.private_role == true ? "Public" : "Private", private_fiture_path(repo), data: { turbo: true, turbo_method: :patch }, class:repo.private_role == true ? "btn btn-warning" : "btn btn-danger" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/repos/edit.html.erb
<h1>Editing repo</h1>

<%= render "form", repo: @repo %>

<br>

<div>
  <%= link_to "Show this repo", @repo %> |
  <%= link_to "Back to repos", repos_path %>
</div>

app/views/repos/index.html.erb
<h1 class="mb-3">
  Repos
  <%= link_to " New repo", new_repo_path, class:"btn btn-dark bi bi-plus-square-fill" %>
</h1>

<div id="repos">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @repos.order(id: :desc).where(private_role: false).each do |repo| %>
      <%= render repo %>
    <% end %>
  </div>
</div>

<div class="my-3">
  <%= render "layouts/components/pagination", obj: @repos.where(private_role: false) %>
</div>

<%= render partial: 'layouts/modals/modal_repo', locals: { repo: @repo } %>

app/views/repos/new.html.erb
<h1>New repo</h1>

<%= render "form", repo: @repo %>

<br>

<div>
  <%= link_to "Back to repos", repos_path %>
</div>

app/views/repos/show.html.erb
<div class="container">
  <div style="min-height:400px;">
  <hr>
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a>
                    <%= link_to @repo.user.username, profile_path(@repo.user), class:"text-decoration-custom" %>
                  </a>
                </li>
                <li class="breadcrumb-item" aria-current="page">
                  <strong>
                    <%= link_to @repo.name, @repo, class:"text-decoration-custom" %>
                  </strong>
                </li>
              </ol>
            </nav>
          </div>
          <div class="col text-end">
            <%= link_to 'Exit', repos_path, class:"btn" %>
            <%= link_to "Edit this repo", edit_repo_path(@repo), class:"btn" if @repo.user_id == current_user.id %>
            <%= link_to 'Destroy', @repo, data: { turbo: true, turbo_confirm:"are you sure?", turbo_method: :delete }, class:"btn btn-danger" if @repo.user_id == current_user.id %>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <div class="list-group mb-4">
      <div class="list-group-item list-group-item-dark">
        <% if @repo.user.avatar.present? %>
          <%= link_to (image_tag(@repo.user.avatar, width:25, height:25, class:"rounded-circle border shadow", style:"object-fit:contain;background:black;", alt:"Avatar")), profile_path(@repo.user) %>
        <% else %>
          <%= link_to (image_tag "https://img.freepik.com/free-icon/important-person_318-10744.jpg?w=2000", width:25, height:25, class:"rounded-circle border shadow", style:"object-fit:contain;background:black;", alt:"Avatar"), profile_path(@repo.user) %>
        <% end %>
        <%= link_to @repo.user.username, profile_path(@repo.user), class:"text-decoration-custom-color" %>
        <span class="badge rounded-pill text-bg-warning">
          Has <%= @repo.folders.count + @repo.items.count %> Items
        </span>
      </div>
      <%= render @repo.folders.where(subfolder_id: nil).order(id: :desc) %>
      <%= render @repo.items.where(folder_id: nil).order(id: :desc) %>
    </div>
  </div>
</div>

<% if @repo.user_id == current_user.id %>
  <%= render 'layouts/modals/modal_form', locals: { repo: @repo, subfolder: nil } %>
  <%= render 'layouts/modals/modal_item_repo', locals: { repo: @repo, folder_id: nil } %>
<% end %>