config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'search#index', as: 'search'
  patch 'repos/:id', to: 'repos#private_fiture', as: 'private_fiture', :via => :update
  resources :profiles, only: :show
  resources :repos do
    resources :folders, only: [:show, :create, :destroy]
    resources :items, only: [:show, :create, :destroy]
  end
  get '/moon', to: 'application#moon', as: 'moon'
  get '/sun', to: 'application#sun', as: 'sun'
  get 'pages/index'
  devise_for :users
  root "pages#index"
end

app/views/layouts/components/_alert.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %><%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/components/_dropdown_navbar.html.erb
<ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
    <li class="nav-item me-2 dropdown d-xxl-none d-xxl-block d-xl-none d-lg-none d-xl-block d-md-none d-lg-block">
        <a class="nav-link" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-search"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-end" style="width:250px;">
            <%= form_tag search_path, method: :get, class:"px-4 py-3" do |f| %>
                <div class="input-group">
                    <%= text_field_tag :q, params[:q], class:"form-control", placeholder:"Search for..." %>
                    <%= button_tag '<i class="fas fa-search"></i>'.html_safe, class:"btn btn-primary", id:"btnNavbarSearch" %>
                </div>
            <% end %>
        </div>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <% if user_signed_in? %>
                <li>
                    <%= link_to "Profile", profile_path(current_user.id), class:"dropdown-item" %>
                </li>
                <li>
                    <%= link_to "Edit profile", edit_user_registration_path, class:"dropdown-item" %>
                </li>
                <li>
                    <%= link_to "Sign out", destroy_user_session_path, data: { turbo: true, turbo_method: :delete }, class:"dropdown-item" %>
                </li>
            <% else %>
                <li>
                    <%= link_to "Sign in", new_user_session_path, class:"dropdown-item" %>
                </li>
                <li>
                    <%= link_to "Sign up", new_user_registration_path, class:"dropdown-item" %>
                </li>
            <% end %>
        </ul>
    </li>
</ul>

app/views/layouts/components/_footer.html.erb
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2022</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>

app/views/layouts/components/_menu.html.erb
<div class="list-group menu">
    <!-- Button trigger modal folder -->
    <button type="button" class="list-group-item list-group-item-action <%= "list-group-item-dark" if cookies[:moon] %>" data-bs-toggle="modal" data-bs-target="#createRepoModal">
        Create new repository
    </button>
    <!-- Button trigger modal folder -->
    <button type="button" class="list-group-item list-group-item-action <%= "list-group-item-dark" if cookies[:moon] %>" data-bs-toggle="modal" data-bs-target="#createFolderModal">
        Create new folder
    </button>
    <!-- Button trigger modal item -->
    <button type="button" class="list-group-item list-group-item-action <%= "list-group-item-dark" if cookies[:moon] %>" data-bs-toggle="modal" data-bs-target="#createItemModal">
        Upload file
    </button>
</div>

<div class="list-group menu2">
    <!-- Button trigger modal folder -->
    <button type="button" class="list-group-item list-group-item-action <%= "list-group-item-dark" if cookies[:moon] %>" data-bs-toggle="modal" data-bs-target="#createRepoModal">
        Test 1
    </button>
    <!-- Button trigger modal folder -->
    <button type="button" class="list-group-item list-group-item-action <%= "list-group-item-dark" if cookies[:moon] %>" data-bs-toggle="modal" data-bs-target="#createFolderModal">
        TEST 2
    </button>
    <!-- Button trigger modal item -->
    <button type="button" class="list-group-item list-group-item-action <%= "list-group-item-dark" if cookies[:moon] %>" data-bs-toggle="modal" data-bs-target="#createItemModal">
        Upload file
    </button>
</div>

app/views/layouts/components/_navbar.html.erb
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <%= link_to "MyRepo", root_path, class:"navbar-brand ps-3" %>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <%= form_tag search_path, method: :get, class:"d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0" do |f| %>
        <div class="input-group">
            <%= text_field_tag :q, params[:q], class:"form-control", placeholder:"Search for..." %>
            <%= button_tag '<i class="fas fa-search"></i>'.html_safe, class:"btn btn-primary", id:"btnNavbarSearch" %>
        </div>
    <% end %>
    <!-- Navbar-->
    <%= render "layouts/components/dropdown_navbar" %>
</nav>

app/views/layouts/components/_pagination.html.erb
<div class="d-flex justify-content-center">
    <%= paginate obj %>
</div>
<div class="text-center">
    <%= page_entries_info obj, entry_name: 'repository' %>
</div>

app/views/layouts/components/_sidebar.html.erb
<nav class="sb-sidenav accordion sb-sidenav-light" id="sidenavAccordion">
    <div class="btn-group text-center my-3 me-3 ms-3 border border-dark" role="group" aria-label="Basic outlined example">
        <% if cookies[:moon] %> 
            <%= link_to 'Light', sun_path, method: :get, class:"btn btn-light" %>
            <a href="#" class="btn btn-dark disabled">Dark</a>
        <% else %>
            <a href="#" class="btn btn-light disabled">Light</a>
            <%= link_to 'Dark', moon_path, method: :get, class:"btn btn-dark" %>
        <% end %>
    </div>
    <div class="dropdown ms-3">
        <a class="btn btn-lg btn-dark dropdown-toggle rounded-pill" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            New
        </a>
        <ul class="dropdown-menu">
            <li>
                <!-- Button trigger modal folder -->
                <button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#createRepoModal">
                    Create new repository
                </button>
            </li>
            <li>
                <!-- Button trigger modal folder -->
                <button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#createFolderModal">
                    Create new folder
                </button>
            </li>
            <li>
                <!-- Button trigger modal item -->
                <button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#createItemModal">
                    Upload file
                </button>
            </li>
        </ul>
    </div>
    <div class="sb-sidenav-menu">
        <div class="nav">
            <div class="sb-sidenav-menu-heading">Core</div>
            <a class="nav-link" href="<%= root_path %>">
                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                Dashboard
            </a>
            <div class="sb-sidenav-menu-heading">Interface</div>
            <a class="nav-link" href="<%= repos_path %>">
                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                Repositories
            </a>
            <%# <div class="sb-sidenav-menu-heading">Interface</div> %>
            <%# <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                Layouts
                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>
            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                <nav class="sb-sidenav-menu-nested nav">
                    <a class="nav-link" href="layout-static.html">Static Navigation</a>
                    <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                </nav>
            </div> %>
            <%# <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                Pages
                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>
            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                        Authentication
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="login.html">Login</a>
                            <a class="nav-link" href="register.html">Register</a>
                            <a class="nav-link" href="password.html">Forgot Password</a>
                        </nav>
                    </div>
                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                        Error
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="401.html">401 Page</a>
                            <a class="nav-link" href="404.html">404 Page</a>
                            <a class="nav-link" href="500.html">500 Page</a>
                        </nav>
                    </div>
                </nav>
            </div> %>
            <%# <div class="sb-sidenav-menu-heading">Addons</div> %>
            <%# <a class="nav-link" href="charts.html">
                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                Charts
            </a> %>
            <%# <a class="nav-link" href="tables.html">
                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                Tables
            </a> %>
        </div>
    </div>
    <div class="sb-sidenav-footer">
        <div class="small">Logged in as:</div>
        Start Bootstrap
    </div>
</nav>